version: '3.7'

services:
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      monitoring:
        ipv4_address: 172.18.238.4

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9102:9102"
    depends_on:
      - node_exporter
    networks:
      monitoring:
        ipv4_address: 172.18.238.6

volumes:
  grafana-storage:

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.238.0/24
