global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 30s

receivers:
  - name: 'telegram'
    telegram_configs:
      - send_resolved: true
        bot_token: '7213774667:AAG3IaZl822wEw5RuSUrZ5jMfgz2sjqszk8'
        chat_id: 5714270447
