global:
  resolve_timeout: 5m

templates:
- 'templates/telegram.tmpl'

route:
  receiver: 'telegram'
  group_wait: 15m
  group_interval: 15m
  repeat_interval: 15m

receivers:
  - name: 'telegram'
    telegram_configs:
      - send_resolved: true
        bot_token: '7213774667:AAG3IaZl822wEw5RuSUrZ5jMfgz2sjqszk8'
        chat_id: 5714270447
        message: '{{ template "telegram.default.message" . }}'
