version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules:/etc/prometheus/rules
    ports:
      - "9090:9090"
    networks:
        monitoring:
            ipv4_address: 172.16.238.2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
        monitoring:
            ipv4_address: 172.16.238.3

  local_node_exporter:
    image: prom/node-exporter
    container_name: local_node_exporter
    ports:
      - "9100:9100"
    networks:
        monitoring:
            ipv4_address: 172.16.238.4

  # cloud_01_node_exporter:
  #   image: prom/node-exporter
  #   container_name: cloud_01_node_exporter
  #   networks:
  #       cloud1net:
  #           ipv4_address: 192.168.20.10

  # cloud_02_node_exporter:
  #   image: prom/node-exporter
  #   container_name: cloud_02_node_exporter
  #   networks:
  #       cloud2net:
  #           ipv4_address: 192.168.30.10

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
        monitoring:
            ipv4_address: 172.16.238.5

volumes:
  grafana-storage:
networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24

  # cloud1net:
  #   driver: bridge
  #   ipam:
  #     config:
  #       - subnet: 192.168.20.0/24

  # cloud2net:
  #   driver: bridge
  #   ipam:
  #     config:
  #       - subnet: 192.168.30.0/24

