version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/rules:/etc/prometheus/rules
    ports:
      - "9090:9090"
    networks:
      monitoring:
        ipv4_address: 172.16.238.2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    networks:
      monitoring:
        ipv4_address: 172.16.238.3

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./config/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      monitoring:
        ipv4_address: 172.16.238.5

  local_node_exporter:
     image: prom/node-exporter
     container_name: local_node_exporter
     ports:
       - "9100:9100"
     networks:
       monitoring:
         ipv4_address: 172.16.238.4

volumes:
  grafana-storage:
networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24