global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - "rules/alert.rules.yml"

scrape_configs:
  - job_name: 'local_node_exporter'
    static_configs:
      - targets: [
        '172.16.238.4:9100',
        '210.245.74.97:5401',
        '210.245.74.97:5501',
        '192.168.2.33:9100'
      ]
    authorization:
      credentials: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE3MjI5MzUwNTAsImV4cCI6MTc1NDQ3MTA1MCwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIkdpdmVuTmFtZSI6IkpvaG5ueSIsIlN1cm5hbWUiOiJSb2NrZXQiLCJFbWFpbCI6Impyb2NrZXRAZXhhbXBsZS5jb20iLCJSb2xlIjpbIk1hbmFnZXIiLCJQcm9qZWN0IEFkbWluaXN0cmF0b3IiXX0.Yu7LiDXG4ygNghqP2jADeLFHY9_TAtb69EUQn1-p6Hv6SFEPQwBEZvIn3BLIOVII8d5LWK7kVKQrUXLUVum6sA'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '172.16.238.5:9093'