global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'
  group_wait: 1m
  group_interval: 1m
  repeat_interval: 5m

receivers:
  - name: 'telegram'
    webhook_configs:
    - url: 'http://192.168.2.10:9102/webhook'
      send_resolved: true