groups:
  - name: example
    rules:
      - alert: HighCpuUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 50
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage detected"
          description: "Instance {{ $labels.instance }} has high CPU usage (> 50%)"
      - alert: TestAlert
        expr: vector(1)
        for: 1m
        labels:
          severity: test
        annotations:
          summary: "This is a test alert"
          description: "This alert is triggered for testing purposes."
