global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - "rules/alert.rules.yml"

scrape_configs:
  - job_name: 'local_node_exporter'
    static_configs:
      - targets: ['172.16.238.4:9100',192.168.2.33:9100]
  
  # - job_name: 'cloud_01_node_exporter'
  #   static_configs:
  #     - targets: ['192.168.20.10:9100']

  # - job_name: 'cloud_02_node_exporter'
  #   static_configs:
  #     - targets: ['192.168.30.10:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - '172.16.238.5:9093'

