global:
  scrape_interval: 15s

rule_files:
  - "rules/alert.rules.yml"

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.16.238.4:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - '172.16.238.5:9093'

