groups:
  - name: test alert_manager monitor
    rules:
      ################ Memory Usage High
      - alert: Memory Usage High
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 50
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Memory Usage (instance {{ $labels.instance }})"
          description: "Memory Usage is more than 50%\n       value = {{ printf \"%.2f\" $value }}%."

      ################ CPU Usage High
      - alert: Cpu Usage High
        expr: (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[1m])) by (instance)) * 100 > 50
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "CPU Usage (instance {{ $labels.instance }})"
          description: "CPU Usage is more than 50%\n       value = {{ printf \"%.2f\" $value }}%."

      ################ Disk Usage
      - alert: Disk Space High
        expr: (node_filesystem_size_bytes - node_filesystem_avail_bytes) * 100 / node_filesystem_size_bytes > 20
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Disk Space Usage (instance {{ $labels.instance }})"
          description: "Disk space usage is over 20%.\n       value = {{ printf \"%.2f\" $value }}%."