groups:
  - name: test alert_manager monitor
    rules:
      ################ Memory Usage High
      - alert: Memory Usage High
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 > 60
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "Memory Usage (instance {{ $labels.instance }})"
          description: "Memory Usage is more than 60%\n VALUE = {{ printf \"%.2f\" $value }}%.\n LABELS: {{ $labels }}"
      
      ################ CPU Usage High
      - alert: Cpu Usage High
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 60
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "CPU Usage (instance {{ $labels.instance }})"
          description: "CPU Usage is more than 60%\n VALUE = {{ printf \"%.2f\" $value }}%.\n LABELS: {{ $labels }}"

      ################ Disk Usage
      - alert: Disk Space High
        expr: (node_filesystem_size_bytes - node_filesystem_avail_bytes) * 100 / node_filesystem_size_bytes > 20
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Disk Space Usage (instance {{ $labels.instance }})"
          description: "Disk space usage is over 20% on {{ $labels.device }}.\nVALUE = {{ printf \"%.2f\" $value }}%.\nLABELS: {{ $labels }}"
